---
- name: Setup remote login
  hosts: [debian]
  vars_prompt:
    - name: "user_password"
      prompt: "Enter a password for user that will sudo"
      private: true
      encrypt: "md5_crypt"
      confirm: true
      salt_size: 7
  roles:
    - { role: whoami, tags: always }
    - { role: sudo, tags: remote }

- name: Are we ready?
  hosts: localhost
  roles:
    - { role: afterwards, tags: always }
