---
- name: setup this machine
  hosts: localhost
  connection: local
  vars_prompt:
    - name: target
      prompt: How you want to refer to this machine
      private: false
      default: "{{ hostname }}"
  tasks:
    - name: get the username running the deploy
      become: false
      ansible.builtin.command: whoami
      register: user

    - name: Create main vars yml for localhost
      template:
        src: vars/localhost.yml.j2
        dest: "{{ playbook_dir }}/host_vars/localhost.yml"
        force: false

    - name: Create vars folder for this hostname
      file:
        path: "{{ playbook_dir }}/host_vars/{{ target }}.localhost"
        state: directory

    - name: Create main vars yml for target
      template:
        src: vars/this.yml.j2
        dest: "{{ playbook_dir }}/host_vars/{{ target }}.localhost/vars.yml"

    - name: Create main vars yml for target
      template:
        src: vars/hosts.j2
        dest: "{{ playbook_dir }}/hosts"
        force: false

    - name: Add target to inventory file when debian.
      lineinfile:
        path: "{{ playbook_dir }}/hosts"
        line: "{{ target }}.localhost"
        regexp: '.localhost'
        insertafter: "debian"
      when: ansible_os_family == "Debian"

    - name: Add target to inventory file when darwin.
      lineinfile:
        path: "{{ playbook_dir }}/hosts"
        line: "{{ target }}.localhost"
        regexp: '.localhost'
        insertafter: "macbook"
      when: ansible_os_family == "Darwin"

    - name: setup passwordless sudo
      include_role:
        name: sudo

    - name: Set a hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ target }}"
