---
- name: Create macfair if directory only if doesnt exist
  file:
    path: "~{{ macbook_user.stdout }}/.macfair"
    state: directory
    force: no

- name: create empty version file only if doesnt already exist
  copy:
    content: ""
    dest: ~{{ macbook_user.stdout }}/.macfair/version
    force: no

- name: add version to file
  lineinfile:
    path: "~{{ macbook_user.stdout }}/.macfair/version"
    line: "{{ parent_role_name }}: {{ hostvars['localhost']['macfair_version'].stdout[1:-1] }}"
    regexp: '{{ parent_role_name }}'
    insertbefore: BOF
  when: hostvars['localhost']['macfair_version'] is defined
