---
- name: Copy debian
  copy:
    src: zsh/debian.zsh
    dest: ~{{ macbook_user.stdout }}/.zsh/debian.zsh

- name: Register ansible location
  become: false
  shell: command python3 -m site --user-base
  register: python_location

- name: Add ansible to path.
  lineinfile:
    path: ~/.zshrc
    line: export PATH="{{ python_location.stdout }}/bin:$PATH"

- name: collect server info
  shell: "curl -H 'User-Agent: keycdn-tools:https://google.com' 'https://tools.keycdn.com/geo.json?host={{ ansible_default_ipv4.address }}' > ~{{ macbook_user.stdout }}/provider.json"

- name: copy motd
  copy:
    src: motd
    dest: /etc/profile.d/motd.sh
  become: true
  become_user: root

- name: Add motd to path.
  lineinfile:
    path: ~/.zshrc
    line: sh /etc/profile.d/motd.sh

- name: register motd.sh exists
  stat:
    path: /etc/profile.d/motd.sh
  register: motd

- name: Conditionally Add motd to path.
  lineinfile:
    path: ~/.zshrc
    line: sh /etc/profile.d/motd.sh
  when: motd.stat.exists

- name: create empty tokens file only if one doesnt already exist
  copy:
    content: ""
    dest: ~{{ macbook_user.stdout }}/.zsh/tokens.zsh
    force: no

- name: create trial file for new functions if one doesn't already exist
  copy:
    content: "tinker(){\n  echo try out new functions here, not in main file\n}"
    dest: ~{{ macbook_user.stdout }}/.zsh/_trialling.zsh
    force: no

- name: copy js help file
  copy:
    src: help.js
    dest: ~{{ macbook_user.stdout }}/.zsh/help.js

- name: register rbenv exists
  stat:
    path: ~{{ macbook_user.stdout }}/.rbenv/bin/rbenv
  register: rbenv

- name: Conditionally Copy zsh rails
  copy:
    src: zsh/rails.zsh
    dest: ~{{ macbook_user.stdout }}/.zsh/rails.zsh
  when: rbenv.stat.exists

- name: Conditionally Add rails to zshrc.
  lineinfile:
    path: ~/.zshrc
    line: source $HOME/.zsh/rails
  when: rbenv.stat.exists
