---
- name: does host file exist?
  stat:
    path: hosts
  register: hosts

- name: display post install message
  debug:
    msg:
      - 'Host file not set up yet. To set it up run the following'
      - 'make thiscomputer'
  when: not hosts.stat.exists
