- name: download elastic
  command: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.1-darwin-x86_64.tar.gz

- name: install elastic
  command: tar xzvf elasticsearch-7.14.1-darwin-x86_64.tar.gz -C ~

- name: remove tar
  command: rm elasticsearch-7.14.1-darwin-x86_64.tar.gz

- name: print role name
  set_fact:
    parent_role_name:  "{{ role_name }}"
