---
- hosts: localhost
  connection: local
  vars:
    default_key: '~/.ssh/id_rsa.pub'
  tasks:
    - debug:
        var: root
    - name: Set up ssh key login for user
      shell: "ssh-copy-id -i {{ item.userkey | default(default_key) }} {{ item.username }}"
      with_items: "{{ root }}"
