---
- name: Register os
  shell: lsb_release -is
  register: os

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install packages required for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ os.stdout | lower }}/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ os.stdout | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  apt:
    name:
      -  docker-ce
      -  docker-compose
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
