- name: Install packages for mac
  import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- name: Install packages for pi
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: print role name
  set_fact:
    parent_role_name:  "{{ role_name }}"

- name: add version
  include_role:
    name: version
