name: Version
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: macfair.io37.ch

    steps:
      - uses: actions/checkout@v3

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-count: "0"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.tag }}"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.version }}"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.clean_changelog }}" > notes.text

      - name: Create Release
        run: gh release create ${{ steps.changelog.outputs.tag  }} --notes-file notes.text
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: make a gitconfig
        run: |
          echo -e "[user]
            name = github-runner
            email = githubrunner@google.fi
          " > ~/.gitconfig

      - name: is gitconfig there
        run: cat ~/.gitconfig

      - name: installs the doc site
        run: npm_config_yes=true npx venlo@latest --appName venlo --language astro --design readme --colorScheme detective

      - name: copies the Docs
        run: cp -r docs/*md venlo/src/content/docs

      - name: copies top level mds
        run: for f in *.md; do cp "$f" "venlo/src/content/top/$(echo "$f" | tr '[:upper:]' '[:lower:]' )"; done

      - name: copies top readme to index
        run: cp README.md venlo/src/content/top/index.md

      - name: Build
        run: cd venlo && make build

      - name: Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: venlo/dist/
          remote_path: "/var/www/html/$DEPLOY_URL"
          remote_host: $DEPLOY_URL
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
